[project]
name = "galatea-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124.4",
    "openai>=2.14.0",
    "requests>=2.32.5",
    "uvicorn[standard]>=0.38.0",
]
